export type ColorPalette = {
  id: string;
  name: string;
  background: string;
  timerBlock: string;
  timerText: string;
  primaryText: string;
  secondaryText: string;
  focusColor: string;
  breakColor: string;
  accentColor: string;
};

export const PALETTES: Record<string, ColorPalette> = {
  warmFocus: {
    id: 'warmFocus',
    name: 'Warm Focus',
    background: '#F8F0D8',
    timerBlock: '#222222', 
    timerText: '#F8F0D8',
    primaryText: '#333333',
    secondaryText: '#999999',
    focusColor: '#4A90E2',
    breakColor: '#FF8C42',
    accentColor: '#B0B0B0',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    background: '#1C1C1E', // Slightly lighter than true black base
    timerBlock: '#3A3A3C', // Contrasts with background
    timerText: '#FFFFFF', // High contrast text inside timerBlock
    primaryText: '#FFFFFF',
    secondaryText: '#8E8E93',
    focusColor: '#0A84FF',
    breakColor: '#FF9F0A',
    accentColor: '#636366',
  },
  sage: {
    id: 'sage',
    name: 'Sage',
    background: '#EAEFE9',
    timerBlock: '#2C3E35',
    timerText: '#EAEFE9',
    primaryText: '#2C3E35',
    secondaryText: '#8A9A92',
    focusColor: '#5A937B',
    breakColor: '#D98A6C',
    accentColor: '#B4C4BC',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    background: '#E6EBEF',
    timerBlock: '#1D2D3D',
    timerText: '#E6EBEF',
    primaryText: '#1D2D3D',
    secondaryText: '#879EAE',
    focusColor: '#4D8AB5',
    breakColor: '#C47761',
    accentColor: '#B5C4D0',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    background: '#FDF7F3',
    timerBlock: '#3D2B1F',
    timerText: '#FDF7F3',
    primaryText: '#3D2B1F',
    secondaryText: '#B19A8D',
    focusColor: '#D36F54',
    breakColor: '#F2A65A',
    accentColor: '#DFCEC5',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    background: '#F4F2F7',
    timerBlock: '#2D283E',
    timerText: '#F4F2F7',
    primaryText: '#2D283E',
    secondaryText: '#A19CB3',
    focusColor: '#8E7CC3',
    breakColor: '#E69E8C',
    accentColor: '#C9C4D9',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome',
    background: '#FFFFFF',
    timerBlock: '#222222', // Subtle dark gray, not too intrusive
    timerText: '#FFFFFF',
    primaryText: '#111111',
    secondaryText: '#888888',
    focusColor: '#444444',
    breakColor: '#777777',
    accentColor: '#CCCCCC',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    background: '#1A2F24', // Use a deep forest green
    timerBlock: '#2D4539', // Lighter block
    timerText: '#EAEFE9', // Light text
    primaryText: '#EAEFE9',
    secondaryText: '#899E93',
    focusColor: '#7BB396',
    breakColor: '#E09F7D',
    accentColor: '#4A5E52',
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    background: '#FFF5F4',
    timerBlock: '#4A2522',
    timerText: '#FFF5F4',
    primaryText: '#4A2522',
    secondaryText: '#C49B99',
    focusColor: '#E57373',
    breakColor: '#81C784',
    accentColor: '#F0C9C7',
  },
  arctic: {
    id: 'arctic',
    name: 'Arctic',
    background: '#F0F6FA',
    timerBlock: '#2E3A45',
    timerText: '#F0F6FA',
    primaryText: '#2E3A45',
    secondaryText: '#99AAB8',
    focusColor: '#64B5F6',
    breakColor: '#FFB74D',
    accentColor: '#CFDCE6',
  },
  vanilla: {
    id: 'vanilla',
    name: 'Vanilla',
    background: '#FDFBF7',
    timerBlock: '#F2ECD9',
    timerText: '#4A4238',
    primaryText: '#332E27',
    secondaryText: '#877B6D',
    focusColor: '#D4C3A3',
    breakColor: '#E6DCC8',
    accentColor: '#B0A289',
  },
  matcha: {
    id: 'matcha',
    name: 'Matcha',
    background: '#F4F7F4',
    timerBlock: '#E3EBE3',
    timerText: '#2D402D',
    primaryText: '#2D402D',
    secondaryText: '#7A9A7A',
    focusColor: '#A3BFA3',
    breakColor: '#C8D9C8',
    accentColor: '#8AA68A',
  },
  blush: {
    id: 'blush',
    name: 'Blush',
    background: '#FFF5F6',
    timerBlock: '#FDE4E6',
    timerText: '#5A3A3D',
    primaryText: '#4A2F32',
    secondaryText: '#AA888B',
    focusColor: '#E6A5AB',
    breakColor: '#F5CBD0',
    accentColor: '#C48187',
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    background: '#FAF9F6',
    timerBlock: '#EBE5D9',
    timerText: '#4D473A',
    primaryText: '#3D382E',
    secondaryText: '#9A9282',
    focusColor: '#D1C2A5',
    breakColor: '#E4DAC5',
    accentColor: '#B5A68A',
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    background: '#F5F7F9',
    timerBlock: '#E4E9F0',
    timerText: '#3A4B5C',
    primaryText: '#2C3A47',
    secondaryText: '#8295A6',
    focusColor: '#A5B9CC',
    breakColor: '#CAD9E6',
    accentColor: '#8C9EB0',
  },
  peach: {
    id: 'peach',
    name: 'Peach',
    background: '#FFF9F5',
    timerBlock: '#FEE5D4',
    timerText: '#5C3826',
    primaryText: '#4A2A1A',
    secondaryText: '#B08876',
    focusColor: '#F5B08C',
    breakColor: '#FAD5C3',
    accentColor: '#D1906F',
  },
  mint: {
    id: 'mint',
    name: 'Mint',
    background: '#F2FBF9',
    timerBlock: '#DDF4EF',
    timerText: '#24524A',
    primaryText: '#1B4039',
    secondaryText: '#7AA39B',
    focusColor: '#96D4C8',
    breakColor: '#C5EBE4',
    accentColor: '#78B0A5',
  },
  lilac: {
    id: 'lilac',
    name: 'Lilac',
    background: '#F9F7FA',
    timerBlock: '#EDE6F2',
    timerText: '#4A3B5C',
    primaryText: '#3A2E47',
    secondaryText: '#9588A6',
    focusColor: '#BDA5D4',
    breakColor: '#DACBEB',
    accentColor: '#9A82B0',
  },
  cloud: {
    id: 'cloud',
    name: 'Cloud',
    background: '#FAFAFB',
    timerBlock: '#EDF0F5',
    timerText: '#3D495C',
    primaryText: '#2C3647',
    secondaryText: '#909BA6',
    focusColor: '#A8B8D1',
    breakColor: '#CCD7E8',
    accentColor: '#8C9EB0',
  },
  oatmeal: {
    id: 'oatmeal',
    name: 'Oatmeal',
    background: '#FAF8F5',
    timerBlock: '#ECE6DF',
    timerText: '#4A423A',
    primaryText: '#3B342E',
    secondaryText: '#9B9084',
    focusColor: '#CDBFAF',
    breakColor: '#E4DCD3',
    accentColor: '#B0A391',
  }
};
